import { fontFamily } from "tailwindcss/defaultTheme";
import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";
import daisyui from "daisyui";

const config: Config = {
  content: ["./src/**/*.{html,js,svelte,ts}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    fontFamily: {
      sans: ["InterVariable", ...fontFamily.sans],
      mono: ["ml", ...fontFamily.mono],
    },
    stylisticSets: {
      zero: "zero",
    },
    extend: {
      typography: ({ theme }) => ({
        primary: {
          css: {
            "--tw-prose-links": theme("colors.pink[500]"),
            "--tw-prose-invert-links": theme("colors.pink[500]"),
          },
        },
      }),
    },
  },
  // daisyui: {
  //   themes: [
  //     "retro",
  //     "business",
  //     "light",
  //     "dark",
  //     "coffee",
  //     {
  //       gruvbox: {
  //         primary: "#b8bb26",
  //         "primary-content": "#0c0d01",
  //         secondary: "#d3869b",
  //         "secondary-content": "#100609",
  //         accent: "#8ec07c",
  //         "accent-content": "#070e05",
  //         neutral: "#3c3836",
  //         "neutral-content": "#d4d3d3",
  //         "base-100": "#282828",
  //         "base-200": "#212121",
  //         "base-300": "#1b1b1b",
  //         "base-content": "#cfcfcf",
  //         info: "#83a598",
  //         "info-content": "#060a08",
  //         success: "#98971a",
  //         "success-content": "#080800",
  //         warning: "#fabd2f",
  //         "warning-content": "#150d01",
  //         error: "#fb4934",
  //         "error-content": "#150201",
  //       },
  //     },
  //     {
  //       "gruvbox-light": {
  //         primary: "#79740e",
  //         "primary-content": "#e2e2d1",
  //         secondary: "#8f3f71",
  //         "secondary-content": "#ead7e1",
  //         accent: "#427b58",
  //         "accent-content": "#d8e4dc",
  //         neutral: "#d5c4a1",
  //         "neutral-content": "#100e09",
  //         "base-100": "#fbf1c7",
  //         "base-200": "#dad2ad",
  //         "base-300": "#bab393",
  //         "base-content": "#15140e",
  //         info: "#076678",
  //         "info-content": "#d1dfe3",
  //         success: "#98971a",
  //         "success-content": "#080800",
  //         warning: "#d79921",
  //         "warning-content": "#110800",
  //         error: "#cc241d",
  //         "error-content": "#fbd8d2",
  //       },
  //     },
  //     {
  //       "kanagawa-base": {
  //         primary: "#98bc6c",
  //         "primary-content": "#080d04",
  //         secondary: "#564176",
  //         "secondary-content": "#dbd6e3",
  //         accent: "#83a598",
  //         "accent-content": "#060a08",
  //         neutral: "#36363f",
  //         "neutral-content": "#d3d3d5",
  //         "base-100": "#1a1a1f",
  //         "base-200": "#151519",
  //         "base-300": "#101014",
  //         "base-content": "#cbcbcd",
  //         info: "#78c0e0",
  //         "info-content": "#050e12",
  //         success: "#98bc6c",
  //         "success-content": "#080d04",
  //         warning: "#efcb68",
  //         "warning-content": "#140f04",
  //         error: "#a91e2e",
  //         "error-content": "#f3d4d3",
  //       },
  //     },
  //     {
  //       "kanagawa-base-light": {
  //         primary: "#405936",
  //         "primary-content": "#d6dcd4",
  //         secondary: "#67597a",
  //         "secondary-content": "#dfdce3",
  //         accent: "#003554",
  //         "accent-content": "#cad3db",
  //         neutral: "#e3e3e8",
  //         "neutral-content": "#121213",
  //         "base-100": "#f4f4f6",
  //         "base-200": "#d4d4d6",
  //         "base-300": "#b5b5b7",
  //         "base-content": "#141415",
  //         info: "#0075a2",
  //         "info-content": "#d2e3ed",
  //         success: "#98bc6c",
  //         "success-content": "#080d04",
  //         warning: "#efcb68",
  //         "warning-content": "#140f04",
  //         error: "#981b29",
  //         "error-content": "#efd3d1",
  //       },
  //     },
  //     {
  //       kanagawa: {
  //         primary: "#98bb6c",
  //         "primary-content": "#080d04",
  //         secondary: "#957fb8",
  //         "secondary-content": "#08060c",
  //         accent: "#b8b4d0",
  //         "accent-content": "#0c0c10",
  //         neutral: "#363646",
  //         "neutral-content": "#d3d3d7",
  //         "base-100": "#1f1f28",
  //         "base-200": "#191921",
  //         "base-300": "#14141b",
  //         "base-content": "#cdcdcf",
  //         info: "#7e9cd8",
  //         "info-content": "#050911",
  //         success: "#76946a",
  //         "success-content": "#050804",
  //         warning: "#e6c384",
  //         "warning-content": "#130e06",
  //         error: "#ff5d62",
  //         "error-content": "#160303",
  //       },
  //     },
  //   ],
  //   darkTheme: "business",
  // },
  plugins: [typography],
};

export default config;
